package programacaofuncionalAndExpressoesLambda.map;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public class EstudoMap01 {
    public static void main(String[] args) {
        List<String> fruit = new ArrayList<>();

        fruit.add("Apple");
        fruit.add("mango");
        fruit.add("pineapple");
        fruit.add("kiwi");

        System.out.println("List of fruit-" + fruit);

        // Versão original
        List list = fruit.stream()
                .map(f -> f.length())
                .collect(Collectors.toList());

        // Versão otimizada
        List<Integer> list2 = fruit.stream()
                .map(String::length)
                .toList();

        System.out.println("ListOne generated by map-" + list);
        System.out.println("ListTwo generated by map-" + list2);

        System.out.println("--------------------------------------");

        List<Integer> lista = Arrays.asList(2, 3, 4, 5);

        List<Integer> lista2 = lista.stream().map(number -> number + 1).toList();

        System.out.println(lista);
        System.out.println(lista2);
    }
}
